SR5-FoundryVTT/SR5-FoundryVTT

lang/de.json, lang/en.json, module/actor/entity.js, module/item/entity.js, module/item/sheet.js, module/migration.js, shadowrun5e.js, system.json, template.json, templates/actor/parts/actor-equipment.html, templates/item/parts/technology.html, templates/item/parts/weapon-ammo-list.html, templates/item/parts/weapon-mods-list.html
This adds the Conceal value on Modifications to count as a modifier for the weapon it is equipped to. This displays in the chat card message.
Also modified the look of the ammo and weapon mod lists to look better.
=> Implement conceal rating mod

src/module/item/SR5Item.ts
=> Issue pdfoundry api changed

src/module/actor/SR5ActorSheet.ts, src/module/item/SR5Item.ts
Also removed dev console.error for points.
=> ActorSheet._onDragItemStart has been removed for _onDragStart.

locale/de/config.json, locale/en/config.json, locale/pt-BR/config.json, src/module/migrator/VersionMigration.ts
Corrected german translation and added additional strings for migration ui.notifications
=> #243 wrong or missing translations

src/module/apps/characterImport/ArmorParser.js, src/module/apps/characterImport/BaseParserFunctions.js, src/module/apps/characterImport/ContactParser.js, src/module/apps/characterImport/CyberwareParser.js, src/module/apps/characterImport/ItemsParser.js, src/module/apps/characterImport/LifestyleParser.js, src/module/apps/characterImport/PowerParser.js, src/module/apps/characterImport/QualityParser.js, src/module/apps/characterImport/SpellParser.js, src/module/apps/characterImport/WeaponParser.js, src/module/apps/characterImport/gearImport/AmmoParser.ts, src/module/apps/characterImport/gearImport/BaseGearParser.ts, src/module/apps/characterImport/gearImport/DeviceParser.ts, src/module/apps/characterImport/gearImport/GearsParser.ts, src/module/dataTemplates.ts, src/module/types/item/Description.ts
Import: All basic information is now imported for all items (rating, cost, availability, concealment) (closes #330)
Import: Imported items now have default image (closes #302)
Import: Continued improving structure of chummer character import. Split the ItemsParser into several individual parsers, centralized parsing of description and technology data and moved several things to the new dataTemplates
=> Small fixes and improvements to the importer

src/module/apps/characterImport/ItemsParser.js
=> Import: Import was broken when armor was imported

README.md
I updated the readme.md and made the link to the wiki and helping out section a bit more obvious. Removed some content that can be found in the wiki now. Probably needs some more work, but it is okay for the moment.
=> Update readme.md with more info

dist/locale/ko/config.json, locale/ko/config.json
correct korean typos
If there is any problem, please tell me.
=> correct korean typos

dist/locale/ko/config.json, locale/ko/config.json
=> v0.7.26 korean translation

dist/locale/ko/config.json, locale/ko/config.json
v0.8.1 korean update
Please tell me, if there is any problem.
=> v0.8.1 korean update

dist/locale/ko/config.json, locale/ko/config.json
0.8.4 korean update
If there is any problem, please tell me.
=> 0.8.4 korean update

.vscode/launch.json
Add a default debug action for VSCode.
Not sure if this is something good to add thise VSCode-specific file to the repo. Let me know if you don't like that.
=> Add an easy debugging command for Edge in VSCode.

public/locale/de/config.json, public/locale/pt-BR/config.json, src/module/actor/sheets/SR5BaseActorSheet.ts, src/module/apps/skills/SkillEditSheet.ts, src/module/handlebars/ItemLineHelpers.ts, src/module/handlebars/SkillLineHelpers.ts, src/module/helpers.ts, src/module/item/SR5Item.ts, src/module/types/template/Skills.ts, src/module/utils/links.ts, src/templates/apps/skill-edit.html, src/templates/item/parts/header.html
The new link for skills works for active / language / knowledge skills.
**New actor view with link icons in skills**
> ![image](https://user-images.githubusercontent.com/13865717/232458740-ed876f05-d234-436e-9dd2-313d9685f43b.png)
**New skill edit sheet with box & link icon**
> ![image](https://user-images.githubusercontent.com/13865717/232459015-39eabc11-c436-405d-81ee-3496ae410ede.png)
#317
=> Add reference links to Skills

src/module/types/item/CritterPower.ts, src/module/types/item/Quality.ts, src/templates/item/critter_power.html, src/templates/item/quality.html, template.json
This closes #768 
This adds system.rating as a value for both qualities and critter powers. This does not add any functionality to them, just makes them referenceable values
=> Added rating value to qualities and critter powers

src/css/bundle.scss
Non-square Actor Artwork squished on Character Sheet design #757
=> Non-squareActor

public/locale/de/config.json
Translations update from [Foundry Hub - Weblate](https://weblate.foundryvtt-hub.com) for [Shadowrun 5th Edition/main](https://weblate.foundryvtt-hub.com/projects/shadowrun5e/main/).
Current translation status:
=> Translations update from Foundry Hub - Weblate

public/locale/en/config.json, src/module/types/item/Contact.ts, src/templates/item/parts/contact.html, template.json
addresses https://github.com/SR5-FoundryVTT/SR5-FoundryVTT/issues/315
=> [FEATURE] Add group option to contacts

src/module/data/DataDefaults.ts, src/module/item/SR5Item.ts, src/module/item/prep/AdeptPowerPrep.ts, src/module/item/prep/SinPrep.ts, src/module/item/prep/functions/ActionPrep.ts, src/module/item/prep/functions/RangePrep.ts, src/module/item/prep/functions/TechnologyPrep.ts, src/module/migrator/Migrator.ts, src/module/migrator/VersionMigration.ts, src/module/types/global.d.ts, src/module/types/template/Technology.ts, src/unittests/quench.ts, src/unittests/sr5.ItemDataPrep.spec.ts
Refactoring SR5Item.prepareData to be more readable and fit SR5Actor.prepareData pattern (more.
=> [CODE] Refactor/item data prep

src/css/bundle.scss, src/css/module.scss, src/templates/actor/tabs/InventoryTab.html, src/templates/actor/tabs/MiscTab.html
Adds in simple calendar support for chat messages to match SR5 chat messages style. 
Fixes for layout from recent css changes
Simple Layout Bug fix #940 #941
Image on the fixes:
=> [LAYOUT][BUG] Feature/simple calendar sr5 css & fixes

src/module/actor/SR5Actor.ts, src/module/actor/flows/DamageApplicationFlow.ts, src/module/actor/sheets/SR5BaseActorSheet.ts, src/module/rules/ConditionRules.ts
Closes https://github.com/SR5-FoundryVTT/SR5-FoundryVTT/issues/921
=> [FEATURE] Mark actor as defeated when taken enough damage

src/templates/actor/tabs/MiscTab.html
Wiill add initiation and Submersion entry field #927 Has preparation for Fade Attribute Selector in the html comment.
=> [LAYOUT] Show initiategrad in sheet ui

public/locale/en/config.json
=> add missing localisation for ritual item type

src/module/apps/characterImport/CharacterInfoUpdater.js, src/module/apps/characterImport/magicImport/InitiationParser.js, src/module/apps/characterImport/technoImport/SubmersionParser.js, src/module/types/actor/Character.ts, src/module/types/actor/Common.ts, template.json
=> [CODE] Split technomancer from magic

src/module/actor/sheets/SR5VehicleActorSheet.ts, src/module/item/SR5Item.ts, src/module/item/SR5ItemSheet.ts, src/module/item/flows/NetworkDeviceFlow.ts, src/unittests/sr5.NetworkDevices.spec.ts
=> [BUG] Commlink PAN breaks items when used in conjunction with Compendium

src/css/foundry.scss
This 'Fixes #905' Will fix the table styling in a journal page table.
=> [BUG] Do Not Force Center In Tables

src/css/actor.scss, src/css/item.scss, src/templates/actor/parts/attributes/FakeAttribute.html
This aims to 'Fixes #1000 #998 #950 #939'
=> Feature/fix Layout Issues Actor & Items

src/module/actor/sheets/SR5BaseActorSheet.ts, src/templates/common/List/ListItem.html
=> [BUG] Fix key binding tooltip and convert to upper case

public/locale/en/config.json
=> [Fix] fix typo in token selection warning

src/module/macros.ts
=> [BUG] rollSkillMacro doesn't return the result of the roll

src/css/actor.scss, src/templates/actor/parts/matrix/SpritePowerList.html
=> [BUG] Sprite Power List Does Not Have A Scroll Bar

src/css/bundle.scss, src/css/effect.scss
=> [LAYOUT] Input Fields Need Contrast

src/module/effect/SR5ActiveEffectConfig.ts
=> [BUG] Active Effect Tabs Need Auto-Save

src/templates/common/List/ListItem.html
=> [BUG] Active Effects Show Click Tooltip

src/module/rules/ActiveDefenseRules.ts, src/module/tests/PhysicalDefenseTest.ts
=> [BUG] Physical Defense Tests allows active defeneses for melee for defense against ranged attacks

public/locale/de/config.json, public/locale/en/config.json, src/module/config.ts, src/module/handlebars/ItemLineHelpers.ts, src/module/tests/MeleeAttackTest.ts, src/templates/apps/dialogs/ranged-attack-test-dialog.html, src/templates/item/ritual.html
=> [BUG] Melee Weapons Have Ammo, But Don't Use It

src/module/config.ts, src/module/item/SR5ItemSheet.ts
=> [FEATURE] Add additional options for Complex Form Matrix Targets

src/module/item/flows/UpdateActionFlow.ts
Will not autofill when an attribute is already given
Fixes #967
=> [FEATURE] Autofill skill attribute when using skill in action

public/locale/de/config.json, public/locale/en/config.json, src/module/actor/SR5Actor.ts, src/module/actor/sheets/SR5SpiritActorSheet.ts, src/module/actor/sheets/SR5SpriteActorSheet.ts, src/module/tests/OpposedCompileSpriteTest.ts, src/module/types/actor/Sprite.ts, src/templates/actor/parts/magic/SpiritOptions.html, src/templates/actor/tabs/matrix/SpriteSkillsTab.html, template.json
=> [FEATURE] Make Defeated Overlay Smarter (and Optional)

src/module/hooks.ts
=> [Feature] only show bulk import button to gm

src/templates/effect/active-effect-config.html
=> [BUG] Change effect help tab wiki link

src/templates/item/call_in_action.html
=> [FEATURE] Summon/Compile Actons Don't Support Active Effects

src/module/types/item/Metamagic.ts, src/templates/item/metamagic.html, template.json
=> [FEATURE] Metamagic Items Don't Have Rollable Actions Integrated

public/locale/de/config.json, public/locale/en/config.json, src/module/effect/SR5ActiveEffect.ts, src/module/effect/SR5ActiveEffectConfig.ts, src/module/effect/flows/SituationModifierEffectsFlow.ts, src/module/rules/WeaponRangeRules.ts, src/templates/effect/active-effect-config.html
=> [FEATURE] Allow applyTo = modifier for test with item

public/locale/de/config.json, public/locale/en/config.json, src/module/tests/CompileSpriteTest.ts, src/module/tests/SummonSpiritTest.ts, src/templates/apps/dialogs/compilation-test-dialog.html, src/templates/apps/dialogs/summonspirit-test-dialog.html, src/templates/item/parts/compilation.html, src/templates/item/parts/summoning.html
=> [BUG] Lock "Spirit/Sprite Type" If "Prep. Spirit/Sprite" Used

src/module/item/ChatData.ts
=> [FEATURE] Add Ritual Descriptors to Actor Spell Tab

.eslintrc.js, src/module/effect/flows/SuccessTestEffectsFlow.ts, src/module/rules/RitualRules.ts, src/module/tests/RitualSpellcastingTest.ts
=> [FEATURE] Improve Ritual Spellcasting Workflow / Initial Roll Card

public/locale/de/config.json, public/locale/en/config.json, src/module/item/prep/HostPrep.ts, src/module/types/item/Host.ts, src/templates/item/host.html, template.json
=> [FEATURE] Custom host matrix attribute values

src/templates/apps/dialogs/ranged-attack-test-dialog.html
=> [FEATURE] Button for recoil-reset in ranged attack dialog

src/css/bundle.scss
=> [BUG] Item Description didn't scale with height

src/module/item/ChatData.ts
=> [FEATURE] Order Weapon Quick Info for range based on range

src/module/effect/autoinline/AutocompleteInlineHooksFlow.ts
=> [BUG] Item-embedded Active Effects can't reference Actor properties.

public/locale/en/config.json, src/module/item/SR5Item.ts, src/module/tests/MeleeAttackTest.ts
=> [BUG] Ammo Warnings Fire for Weapons That Don't Need Ammo

src/module/actor/SR5Actor.ts, src/module/actor/flows/TeamworkFlow.ts
=> [BUG] Starting Teamwork Test not working

src/module/effect/autoinline/AutocompleteInlineHooksFlow.ts
=> [BUG] Debug/Testing Code Left in AutocompleteInlineHooksFlow.ts

src/module/tests/TestCreator.ts
=> [BUG] Opposed Test Doesn't Notify if Actor Doesn't Exist

public/locale/de/config.json, public/locale/en/config.json
=> [BUG] Missing Translation String on Blitz Button

src/templates/actor/parts/vehicle/VehicleSecondStatsList.html
=> [LAYOUT] Allow Vehicle Configration section to scroll

src/module/item/ChatData.ts
=> [BUG] Creating or droppong complex forms no longer break character sheets

src/module/actor/SR5Actor.ts
Also disabled and isSuppressed status was ignored.
=> [BUG] Actor token didn't display temporary effect icons from items and nested items.

src/module/combat/SR5Combat.ts
=> [Fix] add missing combatStart hook

src/module/config.ts
=> [BUG] Missing call_in_action type on item sheet

src/module/actor/sheets/SR5BaseActorSheet.ts, src/module/effects.ts
=> [BUG] Special Handling Needed for "Targeted Actor" Effects

src/module/item/SR5ItemSheet.ts, src/module/item/flows/ActionFlow.ts
=> [BUG] Actions with custom skills wouldn't show their skill on sidebar and actors without this skill

src/module/effect/SR5ActiveEffectConfig.ts
=> [BUG] Test via Item is available on Actor-embedded Active Effects

src/css/foundry.scss
=> [BUG][LAYOUT] Roll Table Descriptive Text Unreadable

src/module/actor/prep/functions/SkillsPrep.ts, src/module/actor/sheets/SR5BaseActorSheet.ts, src/module/apps/dialogs/FormDialog.ts, src/module/apps/skills/LanguageSkillEditSheet.ts, src/module/apps/skills/SkillEditSheet.ts, src/module/data/DataDefaults.ts, src/module/item/SR5Item.ts, src/module/item/SR5ItemSheet.ts, src/module/migrator/VersionMigration.ts
=> [BUG] Deprecation warning for global.mergeObject

src/module/actor/SR5Actor.ts, src/module/actor/flows/DamageApplicationFlow.ts, src/module/apps/importer/actorImport/characterImporter/CharacterInfoUpdater.js, src/module/apps/importer/actorImport/spiritImporter/SpiritInfoUpdater.js, src/module/data/DataDefaults.ts, src/module/helpers.ts, src/module/item/SR5Item.ts, src/module/rules/CombatRules.ts, src/module/rules/SoakRules.ts
=> [BUG] Deprecation warning for global.mergeObject (#1229)

src/module/actor/sheets/SR5BaseActorSheet.ts, src/module/apps/importer/actorImport/itemImporter/magicImport/SpellParser.js, src/module/item/SR5Item.ts, src/module/item/SR5ItemSheet.ts, src/module/tests/OpposedTest.ts, src/module/tests/SuccessTest.ts
v12 removed support for sync enrichtHTML, causing [promise Object] to show for some description fields.
=> [BUG] Item Chat Cards and Actor Items didn't show their descriptions

src/module/apps/itemImport/importer/AmmoImporter.ts, src/module/data/DataDefaults.ts, src/module/helpers.ts, src/module/item/SR5Item.ts, src/module/tests/DroneInfiltrationTest.ts, src/module/tests/DronePerceptionTest.ts, src/module/tests/PilotVehicleTest.ts
Removed usages of document.data.data and document.data.<> in favor of document.system and document.<>
=> [BUG] Removed lingering usage of Document.data shim

src/module/actor/SR5Actor.ts
=> [BUG] Edge isn't reduced when using Second Chance (after) and Push The Limit (before)

src/module/tests/ComplexFormTest.ts
=> [BUG] Fade may not be calculated correctly when resisting

src/module/actor/SR5Actor.ts, src/module/effect/SR5ActiveEffect.ts
=> [BUG] "Targeted Actor" Active Effects Require More Display Refinement

src/module/actor/SR5Actor.ts, src/module/effect/SR5ActiveEffect.ts, src/module/effect/flows/SuccessTestEffectsFlow.ts
=> [BUG] "Targeted Actor" Active Effects Require More Display Refinement #1247

public/locale/de/config.json, public/locale/en/config.json, public/locale/fr/config.json, public/locale/ko/config.json, src/templates/apps/changelog.html, system.json
=> [CODE] Removed bug-reporter module

src/module/template.ts
Fixes #1249
Copied / Update class from latest version of dnd5e, as the original system authors intended and did with their first Template class iteration.
Included dnd5e license according to original code source.
=> [BUG] v12 Placed templates stay as ghost when removed.

src/module/apps/iconAssigner/iconAssign.ts, src/module/apps/importer/actorImport/characterImporter/CharacterImporter.js
=> [Feature] allow imports without file browser permission

src/module/effect/autoinline/AutocompleteInlineHooksFlow.ts, src/module/effect/flows/EnvironmentalChangeFlow.ts, src/module/effect/flows/SituationModifierEffectsFlow.ts
=> [BUG] Thermographic Vision is missing for Active Effects apply-to modifier selection

src/module/actor/sheets/SR5BaseActorSheet.ts, src/module/flows/MatrixFlow.ts, src/module/item/SR5Item.ts, src/module/item/SR5ItemSheet.ts, src/templates/actor/tabs/NetworkTab.html
=> [CODE] Improve matrix attribute selection code

public/locale/de/config.json, public/locale/en/config.json
=> [BUG] Untranslated String in IC Types

public/locale/de/config.json, public/locale/en/config.json, src/module/config.ts, src/module/helpers.ts
=> [BUG] Fixed Helpers.label breaking on non-valid input and added Quality type 'lifemodul'

src/module/canvas.ts
=> [BUG] Drag Ruler locks an actor in place on a square grid

src/module/effect/flows/SuccessTestEffectsFlow.ts
=> [BUG] Extended Test double Active Effects

src/module/effect/flows/SuccessTestEffectsFlow.ts, src/module/tests/SuccessTest.ts, src/unittests/sr5.ActiveEffect.spec.ts
=> [BUG] Test Filters "Natural Recovery Physical" and "Natural Recovery Stun" don't work anymore.

src/templates/item/complex_form.html
=> [BUG] Complex Form template forces opposed tests

src/module/item/flows/ActionFlow.ts
=> [BUG] Odd Interaction with Custom Skills & Actions  Fixes #1293

src/module/tests/SuccessTest.ts, src/templates/rolls/success-test-message.html
=> [BUG] Actions with Damage do not display Incoming if the base value is 0

src/module/tests/SuccessTest.ts
=> [BUG] Fix 0 damage showing on Tests

src/module/item/SR5ItemSheet.ts
_onClipEquip now has a query as to whether the item has an actor or not and reacts accordingly.
Issue #1320
=> Bugfix for #1320

src/module/handlebars/BasicHelpers.ts, src/module/item/flows/NetworkDeviceFlow.ts
=> [BUG] PAN Devices don't show slaved items.

src/module/tests/DroneInfiltrationTest.ts, src/module/tests/DronePerceptionTest.ts
=> [BUG] Limits are inconsistently included in Drone Tests

src/module/actor/prep/functions/SkillsPrep.ts
=> [BUG] Chummer Imported Actors have a broken sheet

src/module/actor/prep/functions/SkillsPrep.ts
* [BUG] Chummer Imported Actors have a broken sheet
Fixes #1338
=> Release 0.23.1

src/module/apps/importer/actorImport/itemImporter/bioImport/QualityParser.js, src/module/apps/itemImport/parser/quality/QualityParserBase.ts
When importing, add karma value
=> [Feature] Add karma values on quality items imported from Chummer5

src/module/handlebars/ActorHelpers.ts, src/templates/actor/parts/vehicle/VehicleSecondStatsList.html
A pretty simple fix honestly, doing the same check 6 times isn't the most elegant solution but it works!
Implements Fixes #1173.
=> [Feature] Auto calculate modification points from body (#1173)

src/module/tests/SuccessTest.ts
=> [BUG] Effects Action Categories didn't work as expected

src/module/apps/itemImport/importer/VehicleModImporter.ts, src/module/apps/itemImport/parser/mod/VehicleModParserBase.ts, src/module/config.ts, src/module/types/item/Modification.ts, src/templates/actor/parts/vehicle/VehicleSecondStatsList.html
=> [Bug] Remove uneeded vehicule modifications categories and fix a bug in the vehicle importer

src/module/handlebars/ActorHelpers.ts
=> [BUG] Vehicle Modification Quantity Not Reflected In Total Slot Cost

src/module/migrator/VersionMigration.ts
=> [BUG] Migration Bug in 0.24.1

public/locale/fr/config.json
Just a tiny change but it makes things more consistent and make the smallest size work
=> [i18n] Harmonize the spirit and sprite french translations

src/css/bundle.scss, src/templates/actor/parts/matrix/MatrixAttribute.html, src/templates/actor/sprite.html, src/templates/actor/tabs/matrix/SpriteSkillsTab.html
Fixes #907.
The only thing I'm not too sure about is the location/size of the "Roll" button (see picture)
=> [BUG] Update the sprite sheet for a consistent look and feel 

public/locale/ko/config.json
korean translation for v0.25.0
=> [i18n] Korean translation for v0.25.0

public/locale/de/config.json, public/locale/en/config.json, public/locale/fr/config.json, public/locale/ko/config.json, public/locale/pt-BR/config.json, src/module/apps/itemImport/importer/VehicleModImporter.ts, template.json
fixes  #1351  that breaks the generation of folders. Plus remove exotic and enhanced from translation files
=> [BUG] Non-RAW Vehicle Modification Types 

src/module/apps/importer/actorImport/itemImporter/armorImport/ArmorParser.js, src/module/apps/importer/actorImport/itemImporter/bioImport/ContactParser.js, src/module/apps/importer/actorImport/itemImporter/bioImport/LifestyleParser.js, src/module/apps/importer/actorImport/itemImporter/bioImport/QualityParser.js, src/module/apps/importer/actorImport/itemImporter/importHelper/SimpleParser.js, src/module/apps/importer/actorImport/itemImporter/magicImport/CritterPowerParser.js, src/module/apps/importer/actorImport/itemImporter/magicImport/PowerParser.js, src/module/apps/importer/actorImport/itemImporter/magicImport/RitualParser.js, src/module/apps/importer/actorImport/itemImporter/magicImport/SpellParser.js, src/module/apps/importer/actorImport/itemImporter/vehicleImport/VehicleModsParser.js, src/module/apps/importer/actorImport/itemImporter/wareImport/WareParser.js, src/module/apps/importer/actorImport/itemImporter/weaponImport/WeaponParser.js
Changed parameter order in IconAssign.iconAssign
Fixes #1418
=> [BUG] Character import doesn't import Armor, Contact, Lifestyle, Quality, Critter Power, Power, Ritual, Vehicle Mod, Ware and Weapon anymore

src/css/bundle.scss, src/templates/actor/parts/skills/LanguageAndKnowledgeSkillList.html
Fixes layout issue #1429  where the container for knowledge skills and language entries was height-locked and clipped its content.
- Replaced `height: 250px` with `min-height: 250px` in `.flexcontainer-skills`
- Open an actor sheet with many knowledge skills or languages
- Verify the list grows with content and nothing is clipped
=> Fix: prevent clipping of knowledge skills and language list

src/module/apps/itemImport/helper/BonusHelper.ts
Misspelled `pain_tolerance_stun`
=> Fix typo in BonusHelper

src/css/effect.scss
=> [Fix] Effect's Change Tab using incorrect layout since v13 support

src/css/bundle.scss
=> [BUG] Can't scroll on long knowledge skill lists

src/css/module.scss
I do not know if this even needs a description.
=> [Bug] Unreadable document links on some chat messages

src/module/item/flows/ItemRollDataFlow.ts
This might overlap with https://github.com/SR5-FoundryVTT/SR5-FoundryVTT/pull/1494 
If so, let me know and we merge there or close this PR. :)
=> Fixed test value resolution unittests failing

src/module/actor/sheets/SR5MatrixActorSheet.ts, src/module/flows/MatrixTargetingFlow.ts, src/module/flows/SocketMessageFlow.ts, src/module/handlebars/ItemLineHelpers.ts, src/module/hooks.ts, src/module/sockets.ts, src/unittests/sr5.SR5Item.spec.ts
Checked for TODO: tam comments and resolved all.
If a todo made changes necessary, a single commit was made for each.
Tested refactor on SocketMessage method into SocketMessageFlow
=> [TODO] Removed todos getting lost in time and space... like ... tears in rain.

public/locale/de/config.json, public/locale/en/config.json, src/module/actor/sheets/SR5MatrixActorSheet.ts, src/module/flows/MatrixTargetingFlow.ts, src/module/handlebars/ItemLineHelpers.ts, src/module/item/flows/MatrixNetworkFlow.ts, src/module/tests/TestCreator.ts, src/module/tests/flows/MarkPlacementFlow.ts
- Fixed bug showing all target icons as 'Persona'
- Kept offline meatbacks visible but marked them as offline
- Show error when selecting offline target for matrix actions
=> [Feature] Show and inform about offline targets on sheet

src/module/item/SR5ItemSheet.ts
Ran into this while working on invite-mark action and creating more complex pans
=> [Bugfix] Fix dropping master devices onto a weapon

src/module/apps/itemImport/helper/BonusHelper.ts, src/module/effect/SR5ActiveEffectConfig.ts, src/module/migrator/versions/Version0_30_3.ts, src/module/types/fields/TagifyField.ts, src/module/utils/sheets.ts
This fixes #1580 and also fixes #1545.
Shows previous invisible tag, and change the order of the tabs.
=> [BUG] Invisible Filter Imported with Bulk Importer

src/module/migrator/Migrator.ts, src/module/migrator/versions/Version0_30_6.ts, src/module/types/actor/IC.ts, src/module/types/actor/Spirit.ts, src/module/types/actor/Sprite.ts, src/module/types/actor/Vehicle.ts, src/module/types/item/Host.ts, system.json
Fixes #1566 
This change non-mutable value to its intended value for existing documents.
=> [BUG] Set fixed read-only values to its correct value.
