css/main.css
lang/en.json
module/actor/entity.js
module/apps/gmtools/OverwatchScoreTracker.js
scss/main.scss
shadowrun5e.js
templates/apps/gmtools/overwatch-score-tracker.html

Adds an Overwatch Score Tracker to the system, available in the Basic Tools Menu.
There's an issue with rollMode in the current versions of Foundry it seems so I'm not outputting the roll card for the moment.
Version number in system.json will need to be updated, I wasn't sure if that was something you can do as part of the PR or how we want to handle that.

Overwatch score tracker

---

src/module/actor/SR5ActorSheet.ts
src/module/apps/skills/KnowledgeSkillEditForm.ts
src/module/apps/skills/SkillEditForm.ts
src/module/item/SR5ItemSheet.ts

- Fix overwriting skills by only allowing one skill app to open.
- Fix reopening ItemSheets due to update latency above closing animation length

Reported issue with overwriting skills and reopening item app windows

---

src/templates/actor/parts/ActionList.html

Creating a new actor action didn't work, due to actor/sheet rework:

Added missing item type back to action creation

---

locale/de/config.json
locale/en/config.json
src/module/chat.ts
src/module/constants.ts
src/module/item/SR5Item.ts
src/module/rolls/ShadowrunRoller.ts
src/module/settings.ts

Allow gamemasters to choose wether they want to use the token or the actor name / img for roll chat messages using a system setting.
Should a roll be initiated from within the actorsheet without a token placed on map, the actor name / img will be used, even if otherwise stated in the settings.
Should a custom name / img be used, that doesn't match the actor name / img, this will be used instead, allow item rolls to still function unaffected.

Chat names from tokens

---

locale/de/config.json

JSON parser beeing very correct with it's handling of a trailing comma.

Removed trailing comma

---

src/module/constants.ts
src/module/helpers.ts
src/module/item/SR5Item.ts

Didn't find the actual conversion of arrays into index objects, so I rebuild getEmbeddedItems a bit and used the same kind of solution.
Also: System / Module Active Effects are stored as an array in the Entity.data field, however Foundry converts that into a Collection in Entity.effects. The actual item data fits that and it's only after the setFlag/getFlag flow that it Entity.data.effects breaks.

Fixed embeddedItems ActiveEffects datatype after setFlag/getFlag flow.

---

README-DEV.md
docker-compose.yml
src/module/actor/prep/CritterPrep.ts

This should fix #289 to correctly show `Stun`.
I also added `docker-compose.yml` file that I used to run a local instance for testing with `podman`.
Not sure if you want this - if not I can quickly rebase that commit out of this MR.

Fix critter stun track

---

dist/templates/apps/import.html
src/module/actor/prep/functions/SkillsPrep.ts
src/module/apps/characterImport/CharacterInfoUpdater.js
src/module/apps/characterImport/ItemsParser.js
src/module/apps/characterImport/gearImport/AmmoParser.ts
src/module/apps/characterImport/gearImport/BaseGearParser.ts
src/module/apps/characterImport/gearImport/GearsParser.ts
src/module/apps/characterImport/gearImport/ParserSelector.ts
src/module/apps/chummer-import-form.js
src/templates/apps/import.html

Import: Added support for description, background, concept and notes (closes #300)
Import: Added support for contacts (group contacts are handled as normal contacts for now) (closes #301)
Import: Added support for lifestyles (closes #310)
Import: Fixed adept power points import (fixes #308)
Import: Languages were not correctly imported because language.value was setup as an array instead of an object (fixes #316)
Import: Ammunition is now marked as ammo and the stats are imported - however it cannot yet be equipped into a weapon :( (fixes #309)
Import: Fixed pilot watercraft skill import 
Import: Added skill name to adept power "Improved skill"
Import: Grenades & rockets are no longer imported twice (previously they were in weapons and gear section)
Import: Added rating for gear items, …

Small bugfixes and improvements in the chummer import

---

src/module/importer/importer/AmmoImporter.ts

If foundWeapon is undefined, `foundWeapon !== null` is true, but accessing foundWeapon.data crashes.
It happens when using fr_data for localization

Corrected crash in ammo importer

---

dist/bundle.js
src/module/hooks.ts
src/module/token/SR5Token.ts

The token resource bars are designed to function like health bars, with
a full status being good and an empty status being bad. They are
color-coded accordingly with, empty being red and full being green on
the primary resource bar.
The Shadowrun condition monitor works oppositely, however, with full
being bad and empty being full.
This commit flips the value of the token's copy of the condition
monitor resources just before they are drawn so they draw correctly
when drawn as health bars.
Fixes #474

Treat condition monitors like health bars

---

dist/locale/en/config.json
locale/en/config.json

We spent far too long looking for the `Meatspace Dice` field since all the others are `X Init Dice`, so I updated it to match.

Update Meatspace Initiative modifier labels to match other initiative modifiers

---

gulp.tasks.js

Make an error when running link command and the system folder is not ready for linking.

Better `gulp link` output

---

public/locale/en/config.json
public/locale/fr/config.json
src/css/bundle.scss
src/module/actor/sheets/SR5BaseActorSheet.ts
src/module/handlebars/BasicHelpers.ts
src/module/handlebars/ItemLineHelpers.ts
src/templates/actor/tabs/InventoryTab.html

Here is a proposition to have collapse/expand feature on item categories with the following properties:
- One icon added to the end of the section line to toggle visibility
- 2 icons added to the inventory heeder line to collapse/expand all sections at once
- When collapsed, the title of the section is greyed out to give a visible hint that the section is not just empty
- Adding an item to the section opens it
- The state is not persisted in the server storage
- The state is not per inventory, only per section (changing inventory won't change the visibility settings
**New default interface**
> ![image](https://user-images.githubusercontent.com/13865717/230746874-26ea0b26-511b-41dc-8ba6-90163dc09717.png)
**With some section collapsed**
> …

Add Collapse / Expand options on inventory categories.

---

public/locale/en/config.json
src/module/actor/sheets/SR5BaseActorSheet.ts
src/module/apps/characterImport/gearImport/DeviceParser.ts
src/module/config.ts
src/module/data/SR5ItemDataWrapper.ts
src/module/importer/importer/DeviceImporter.ts
src/module/item/ChatData.ts
src/module/item/SR5Item.ts
src/module/types/item/Device.ts

This is my first PR to this repo (and to any Foundry system); please give me feedback if anything needs modification or improvement!
Changeset:
- Add support for Rigger Command Consoles (RCCs)
- Add to Chummer parser types
- Add to data importer as its own folder
- Consume RCC and Commlink ASDF (primarily Data Processing and Firewall) for Matrix stats on Actors, affecting Matrix tests and the Matrix tab
- Modify Chummer import to parse ASDF matrix attributes as integers (not sure if this caused any issues before)
- Fix Chummer import Data Processing attribute - it would previously always return 0 for all types of devices (commlinks, RCCs, and cyberdecks), due to keying off "systemprocessing" instead of "dataprocessing"
To Consider:
- Translations - I wasn't sure if "Rigger Command …

Add RCC (Rigger Command Console) Support

---

src/module/importer/parser/weapon/MeleeParser.ts
src/module/importer/parser/weapon/RangedParser.ts
src/module/importer/parser/weapon/ThrownParser.ts
src/module/importer/parser/weapon/WeaponParserBase.ts
src/unittests/quench.ts
src/unittests/sr5.WeaponParser.spec.ts

This changeset commonizes the damage parsing logic between melee, ranged, and throwing weapons.  The previous logic failed to parse strength-based melee weapons - perhaps this is due to a breaking change in chummer data.  It also makes an attempt to parse previously unparsed data, such as Electricity and Fire elemental damage.  Finally, it adds some unit tests around the damage parsing logic; these tests should eventually be expanded to cover the rest of the logic within the weapon parser base class and subclasses.

Fix and commonize chummer parser damage logic for Weapons

---

src/module/actor/sheets/SR5BaseActorSheet.ts
src/module/helpers.ts

This changeset fixes creation of knowledge skills by keying off the "list-header" class instead of the "list-item" class.  The current behavior throws an error trying to add any knowledge skill except Language skills, with the following exception:
```
helpers.ts:119 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'dataset')
at Helpers.listItemId (helpers.ts:119:56)
at SR5CharacterSheet.<anonymous> (SR5BaseActorSheet.ts:1350:34)
...
```
I also re-enabled showing the Edit Form after creation - it seems to work now, so I suspect the aforementioned issue was the root cause.  I'd love to figure out how to write unit tests for this behavior, but I'm not sure how you'd go about rendering HTML forms as part of the quench tests.

Fix creation of knowledge skills

---

src/css/item.scss
src/module/actor/SR5Actor.ts
src/module/actor/sheets/SR5VehicleActorSheet.ts
src/module/item/ChatData.ts
src/module/item/SR5Item.ts
src/module/item/SR5ItemSheet.ts
src/module/item/flows/NetworkDeviceFlow.ts
src/module/types/actor/Vehicle.ts
src/templates/actor/parts/vehicle/VehicleSecondStatsList.html
src/templates/actor/tabs/NetworkTab.html
src/templates/item/parts/matrix.html
src/unittests/sr5.NetworkDevices.spec.ts

- Allows vehicles to be added to PANs via drag-and-drop
- Shows PAN on vehicle actor's sheet
- Attempts to unify the network logic to accept either items or actors seamlessly
- Adds a new `networkController` key onto vehicle actor data
- Updates matrix device item edit page to not allow shuffling ASDF stats on RCCs, in addition to showing stats for commlinks to support things like oddmods (see #784 )
RCC Matrix Stats (Commlink looks identical):

Allow vehicles to be added to PANs and improve matrix device item edit page

---

src/module/actor/sheets/SR5BaseActorSheet.ts
src/module/handlebars/BasicHelpers.ts
src/module/item/SR5ItemSheet.ts
src/templates/item/parts/matrix.html

Addresses #830 
* Allow hosts to once again shuffle their ASDF matrix attributes (broken in #804 - sorry!)
* Update shuffling logic to swap slots similar to the logic on the Matrix tab of the Actor sheet
See demo:
https://github.com/smilligan93/SR5-FoundryVTT/assets/2165323/892c098c-753c-4aea-9f18-cdb67838f504

Fix unshuffleable host matrix attributes and add logic to swap slots when shuffled

---

gulp.tasks.js
package-lock.json
package.json

This is a breaking change in the node modules and gulp toolchain.
Devs will have to `npm install` to update their local node modules

Updated esbuild and typecheck

---

public/locale/en/config.json
src/module/actor/SR5Actor.ts
src/module/rules/CombatRules.ts
src/module/tests/PhysicalDefenseTest.ts
src/unittests/sr5.AttackTests.spec.ts

Similar to vehicle armor, this changeset applies the rules for hardened armor during the physical defense test such that if `modified DV < modified AV`, the attack automatically does no damage.

Apply Hardened armor rules during physical defense test

---

src/css/bundle.scss
src/css/config/_mixins.scss
src/templates/actor/parts/matrix/ProgramList.html
src/templates/actor/tabs/InventoryTab.html
src/templates/actor/tabs/MiscTab.html

will move the new css classes scroll-area-skills etc to scroll-area so the update function remembers the last scroll position. Hover improvements on item and header hover

[BUG] Re-implement saving of scroll position on document update

---

src/module/apps/characterImport/bioImport/QualityParser.js
src/module/apps/characterImport/importHelper/BaseGearParser.ts

This fixes the bug mentioned in the discussion of https://github.com/SR5-FoundryVTT/SR5-FoundryVTT/issues/932. With this, all imported items should be marked correctly on actor sheets and imported qualities should have a correct data structure.

[BUG] Character Import. Qualities and Equipment import issues

---

src/module/tests/RangedAttackTest.ts
src/module/tests/SuccessTest.ts
src/module/types/global.d.ts
src/module/types/template/weapon.ts

Due to this the targetActorUuids where always empty, causing them to not be available for any opposed tests.
While opposed tests otherwise worked with only targeted actors, this caused physical defense tests after ranged attacks to not have any targets available and always need selections. Since only ranged attacks have functionality around token targeting, this caused the misinterpretation that targeting doesn't do anything besides showing targets on message.
@Stexinator since you've been working on opposed test not preselecting targets, could you review this PRs assumption that now all opposed tests use targets to roll with, when no token is selected.

[BUG] RangedAttackTest did filter actor uuids using token uuids

---

src/templates/actor/parts/vehicle/VehicleStatsList.html

Resolves #1073 
Recent changes made in #1029 broke editing of vehicle stats for all stats except Body and Armor. This changeset restores the correct behavior.
Note - the `rollId` field has no effect for all vehicle stats except body and armor.  There is a stub implementation at [SR5BaseActorSheet.ts#685](https://github.com/SR5-FoundryVTT/SR5-FoundryVTT/blob/master/src/module/actor/sheets/SR5BaseActorSheet.ts#L685).

[BUG] Fix editing of vehicle stats

---

src/module/effect/SR5ActiveEffect.ts

[BUG] The ternary operator and math function don't work with active effects

---

src/module/actor/SR5Actor.ts

addresses https://github.com/SR5-FoundryVTT/SR5-FoundryVTT/issues/1168
I orderd getSkillByLabel according to expected amount. The number of entries should be so low anyway that it should have no impact on performance
Additionally, this enabled to use TeamworkTests with the displayed name instead of the internal id, making it easier to use for non-english speaker

[Feature] add getSkillByLabel fallback for getSkill when not found

---

src/module/actor/SR5Actor.ts

[BUG] Show all temporary active effects on token, instead of only apply-to actor effects

---

package-lock.json
public/locale/en/config.json
src/module/config.ts
src/module/data/SR5ItemDataWrapper.ts
src/module/handlebars/ActorHelpers.ts
src/module/handlebars/ItemLineHelpers.ts
src/module/item/SR5ItemSheet.ts
src/module/types/actor/Vehicle.ts
src/module/types/item/Modification.ts
src/templates/actor/parts/vehicle/VehicleSecondStatsList.html
src/templates/item/parts/modification.html
template.json

- Added 'drone' Gear Modification type
- Slots only, no Modification Categories
- Updated Vehicle modifications for Drones:
- Adjusted appearance of Modification Categories so it only appears when Vehicle is not a drone
- Added Mod Points section to appear when Vehicle is a drone
- Added Mod Points field
- Added mod points lots used calculation
Bug Fix:
- Added default value for power_train mod category (0)

#1171 - Drone Modifications support

---

src/module/apps/gmtools/OverwatchScoreTracker.js

Fixes issue #1237
Foundry v12 removed .data support, causing token.data.actorLink to fail.
Test both in v12 and v11.

Fix adding linked token actors to Overwatch Score Monitor

---

src/module/actor/SR5Actor.ts

While only allowing a single item of a type to be equipped at a time, if only one item of this type is owned, allow this one item to be unequipped.
Fixes #1273

[BUG] Can't unequip a Commlink

---

src/module/handlebars/BasicHelpers.ts
src/templates/actor/tabs/EffectsTab.html

Mistaken use of Handlebar helper or 
Refactor or for boolean comparisons to avoid future missuse.
Implement firstDefined instead of previous or for using the first defined value, extending it's use from two to n params.
Fixes #1294

[BUG] Spirit Importer Button is gone

---

public/locale/en/config.json
src/module/actor/sheets/SR5BaseActorSheet.ts
src/module/apps/gmtools/OverwatchScoreTracker.js
src/module/item/SR5ItemSheet.ts
src/module/types/item/Quality.ts
src/templates/actor/tabs/EffectsTab.html
src/templates/item/quality.html

adds the ability to drag and drop effects between actors and items. Effects displaying for items on the actor had to be tweaked but it looks to work. 
The only limitation I did with the copying is "test via item" cannot be added to an Actor. 
This also includes a fix for the +15 min Overwatch score bug

[Feature] Add ability to Drag and Drop Active Effects

---

.github/workflows/release.yml

Reworked manifest update to use jq and sponge. Without sponge jq doesn´t support writing back into the source file without weird workarounds.
Reworked CD deployment to read values from manifest.
Removed as many external action dependencies as possible

[CICD] Support for version and compatibility 

---

public/locale/de/config.json
public/locale/en/config.json
src/module/actor/sheets/SR5BaseActorSheet.ts
src/module/apps/skills/SkillEditSheet.ts
src/module/config.ts
src/module/handlebars/ItemLineHelpers.ts
src/module/item/SR5Item.ts
src/module/item/SR5ItemSheet.ts
src/module/item/sheets/SR5CallInActionSheet.ts
src/module/rules/RangedWeaponRules.ts
src/module/types/item/Weapon.ts
src/module/utils/links.ts
src/module/utils/sheets.ts
src/templates/item/parts/header.html
src/templates/item/parts/weapon.html
src/unittests/sr5.RangedWeapon.spec.ts
template.json

I have put two dropdowns in the weapon action tab.
An ammunition bar that reflects which ammunition is currently equipped and which can also be used to equip ammunition.
For ranged weapons there is also a dropdown for clip types. Here you can set which clip type you use with the weapon. Several different possible types are so rare that the code effort is not worth it, in my opinion.
In the inventory, reloading is now divided into up to two buttons. One for reloading to full weapon capacity and one for partial reloading. If a clip type with a (complex) action can only be reloaded x rounds, this number is displayed and only this number is reloaded when clicked. If (during a fight, I don't assume that how fast you get rounds into a spare clip or a drum is relevant enough) it is a clip type …

[Feature] Implement spare clip types und partial reloading

---

.github/workflows/release.yml

Fixes #1310
This will only change the url reported to foundry for the package page when the system is displayed.

[BUG] System package page shows old repo url for notes

---

src/module/tests/OpposedSummonSpiritTest.ts
src/templates/rolls/opposed-actor-creator-message.html

- [Bug] When using prepared Spirit actor for summening a new spirit would be created
- [BUG] Can no longer drag and drop summoned spirits onto the canvas in Foundry v12
Fixes #1324

[Bug] Prepared Spirit summons would create new spirit and summoned spirit wasn't draggable from chat message

---

src/module/constants.ts
src/module/data/DataStorage.ts
src/module/hooks.ts
src/module/settings.ts
src/module/sockets.ts

Introduce a hidden world scope setting used as a general data storage outside of individual FoundryVTT documents.
The DataStorage.ts is introduced to improve usability and handle these edge cases:
- Foundry doesn´t diff on update but overwrite the setting as a whole (#set method)
- Foundry disallows players to set world scope settings. For players send a GM only socket message to handle storage saves by players.
I also extended the SocketMessage.emitForGM method to actually check if any GM are online to avoid 'why is nothing happening' states when only players are online.

[Code] Support for a global data storage with GM socket handling using world settings.

---

src/module/actor/prep/SpiritPrep.ts
src/module/actor/prep/functions/AttributesPrep.ts
src/module/constants.ts

Fixes #1090
The system doesn't differentiate between setting intial value ratings and calculating their value later on.
This fix will make 90% of all cases where an effect should reduce an attribute to zero possible, while preserving the spirit attribute calculation setting their values to 1, even if not enough force has been used to do so.
A better approach would separate between actor creation and data preparation, possibly using the _create and _update method on SR5Actor to set initial base ratings, while still calculating actual values during data preparation.

[BUG] Attributes cannot be reduced to 0

---

src/module/actor/prep/CharacterPrep.ts
src/module/actor/prep/CritterPrep.ts
src/module/actor/prep/ICPrep.ts
src/module/actor/prep/SpiritPrep.ts
src/module/actor/prep/SpritePrep.ts
src/module/actor/prep/VehiclePrep.ts
src/module/actor/prep/functions/SkillsPrep.ts

Fixes #1058
template.json has incomplete data for each skill, missing base. Since base is used during effects apply the field is missing and therefore undefined. This causes it to be ignored during the upgrade apply as it only supports boolean and number.
Missing data was already injected into all skills during preparation of derived data. As effects are applied between base and derived data prep, the data injection was moved to base prep.

[BUG] Active Effects can't Upgrade from Zero

---

.github/workflows/release.yml

When selecting the prerelease instead of latest, the deploy step will be skipped, but the release files will still be attached to the release.

[Code] Allow for a prerelease Release to not deploy to foundry packages

---

src/module/apps/itemImport/importer/CritterPowerImporter.ts
src/module/apps/itemImport/importer/SpritePowerImporter.ts
src/module/apps/itemImport/parser/critter-power/CritterPowerParserBase.ts

Divide the Critter Power in categories, since it has over 300 items.
Also fix bug that adds `Pounce (Infected)` twice.

[Chummer] Critter Powers will be imported with folders for categories

---

src/module/chatMessage/SR5ChatMessage.ts

Fixes #1319
This is the new behavior, that matches default Foundry roll messages (except in detail of what's rendered).

[BUG] Blind GM rolls are no longer blind

---

src/module/utils/links.ts

Editing items with an HTML source caused this error:
> foundry.js:655  Error: An error occurred while rendering SR5ItemSheet 43. Invalid number of embedded UUID parts
> [Detected 1 package: system:shadowrun5e(0.24.3)]
>     at Hooks.onError (foundry.js:654:24)
>     at 🎁Hooks.onError#0 (libWrapper-wrapper.js:188:54)
>     at foundry.js:5795:13Caused by: Error: Invalid number of embedded UUID parts
> [Detected 1 package: system:shadowrun5e(0.24.3)]
>     at Object.parseUuid (foundry-esm.js:3571:37)
>     at LinksHelpers.isUuid (links.ts:50:32)
>     at LinksHelpers.isURL (links.ts:32:26)
>     at get sourceIsUrl (SR5Item.ts:925:29)
>     at SR5ItemSheet.getData (SR5ItemSheet.ts:234:38)
>     at async SR5ItemSheet._render (foundry.js:5838:18)
>     at async SR5ItemSheet._render …

[BUG] fixed uuid error

---

src/module/actor/sheets/SR5BaseActorSheet.ts
src/module/item/SR5Item.ts

Defined two hooks for item-events: SR5_PreActorItemRoll and SR5_PreCastItemAction. The first is needed in the upcoming sr-implementation in the [item-macro-module](https://github.com/Foundry-Workshop/Item-Macro/)

2 hooks for Item Events

---

src/module/apps/SituationModifiersApplication.ts

1. Select token(s).
2. Right click 
3. Click `Toggle Combat State`.
4. Nothing happens, but a bug: `Error: Error thrown in hooked function 'onRenderTokenHUD' for hook 'renderTokenHUD'. html.find is not a function`

[Bug Fix] Adding token to combat not working

---

src/templates/actor/parts/attributes/FakeAttribute.html

Characters have the initiation attribute set, while spirits don´t. The FakeAttribute helper still tries showing an attribute, even if it doesn't exist.
Fixes #1423

[BUG] Spirit Sheet shows unuseable value 'Base' input

---

src/module/actor/SR5Actor.ts

Refactor `getToken` into:
```js
/**
* Returns the most appropriate token document for the actor.
*
* Priority:
* 1. Synthetic token (if this actor is synthetic).
* 2. A controlled linked token on the canvas.
* 3. Any linked token on the canvas.
* 4. Null if no token is available.
*
* @returns The token document if available, otherwise null.
*/
```

[Fix] getToken not working when linked token exist but is not default

---

.prettierrc

All files currently use `'lf'` as the end-of-line character, as confirmed: [here in Discord](https://discord.com/channels/170995199584108546/715689255606681660/1392863695843098727) by [MatyeusM](https://github.com/MatyeusM).
However, the current incorrect configuration can cause every line in a file to appear changed unnecessarily, breaking `git blame` functionality. This issue is demonstrated in: https://github.com/SR5-FoundryVTT/SR5-FoundryVTT/commit/43f19b8dbd7d7e755c7ca169de186f3280b67116.
Therefore, I recommend enforcing `'lf'` as the standard end-of-line setting to maintain consistent file formatting and accurate version history tracking.

[Code] Fix Inconsistent EOL Settings to Preserve Git History

---

gulp.tasks.js
package-lock.json
package.json
tsconfig.json

This PR adds support for path aliasing using `@`, currently configured to point to the `src/` folder. This allows us to replace deep relative imports like `../../hooks` with cleaner, absolute-style imports such as `@/module/hooks`.
While this PR doesn't yet refactor existing imports to use the alias (to avoid conflicts with upcoming large PRs), it lays the groundwork for doing so in the future. We may also consider adjusting the alias to point directly to `src/module` instead, which would enable imports like `@/hooks`.
This should help reduce header clutter and improve code readability going forward. I am sorry, I know hooks is a bad example; but you get what i mean.

[Code] Add path alias support for TypeScript imports

---

src/module/rules/ConditionRules.ts

Basically, it fixes a bug when:
1. Create a new actor (drag into scene to visually see it)
- `Body` value will be at 0.
2. Change any track value
3. The token will be shown as dead.
So, in addition to check whether the overflow is full, it checks whether physical track is also full.

[Fix] Character considered dead if overflow.max = 0;

---

src/module/data/SR5ItemDataWrapper.ts

This fixes critter and sprite power active effects to not apply when the power isn't enabled

[Bug] Fix active effects on critter powers applying when disabled

---

src/templates/actor/sprite.html

[BUG] German Locale: Sprite sheet condition monitor cutting of label 'Zustandsm(onitor)'

---

src/css/actor.scss
src/css/bundle.scss

Fix #1472 by fixing the flex-layout instead of hacking a height.

[Layout] Correct wrong use of flex styling causing need for fixed heights on scroll areas

---

src/css/bundle.scss

Before:
After (excuse me for the color difference, it is from the scss branch):

[Layout] Vertically center text in list-items in lists

---

src/templates/apps/dialogs/matrix-test-dialog.hbs
src/templates/chat/matrix-test-message.hbs

Previously it would look like this:
- icon list uses token name / img
- test dialog uses actor name / img
- test message uses actor name / img
Now all three places use the token name / img. Devices (items) are handled within the speakerName helper, so both actors and icons can be combined with the speakerName helper.

[Bug] Use speaker name across matrix dialog and messages consistently, use speakerName helper

---

src/module/actor/SR5Actor.ts
src/module/actor/flows/MatrixICFlow.ts
src/module/item/flows/MatrixNetworkFlow.ts
src/module/types/template/Matrix.ts

- store the last used grid uuid for later reconnecting or information retrieval
- It's stored on document system data as it's only needed on document. Network information is stored in global storage since it's both needed by the master and slave of each network relationship, to faciliate quick access from both sides without having to parse all world documents.
- When connecting to any grid it will be stored as last (`system.matrix.grid`)
- When disconnecting a host, try to reconnect to the last stored grid
- When disconnecting a grid, allow user to have no network connection at all
- Last used grid will not be cleared when disconnecting grid, connecting a host after and then disconnecting will auto connect to whatever last used grid

[Feature] Reconnect on last used grid when disconnecting / deleting host mark

---

src/module/actor/SR5Actor.ts
src/module/hooks.ts
src/module/item/SR5Item.ts
src/module/item/flows/ItemMarksFlow.ts
src/module/item/flows/MatrixNetworkFlow.ts
src/module/storage/NetworkStorage.ts
src/module/token/SR5TokenDocument.ts

This handles token and sidebar actors to disconnect from networks. Items will also remove all slaved items.
I noticed that the Actor _preDelete was not being called when a token actor was deleted. Luckily that appears to be what SR5TokenDocument is being used for so I implemented it there as well.

[BUGFIX] Disconnect from network and cleanup MARKs upon being deleted

---

public/locale/en/config.json
src/module/actor/SR5Actor.ts
src/module/actor/sheets/SR5MatrixActorSheet.ts
src/module/flows/StorageFlow.ts
src/module/helpers.ts
src/module/item/SR5Item.ts
src/module/item/flows/MatrixNetworkFlow.ts
src/module/storage/MarksStorage.ts
src/module/storage/NetworkStorage.ts
src/module/token/SR5TokenDocument.ts
src/templates/actor/tabs/MiscTab.hbs

This was meant to speed up the deletion of actors as disconnecting all items can take some time. It now shows a progress bar to let users know what is happening.
During this, I found a bug in the way we were storing Mark data for token actors. I fixed that up as well.
Adding devices to your PAN is now much faster at the expense of not refreshing the items that are being updated. I think this is an okay sacrifice given the speed increase.

[Bugfix] Clean up deletion of actors and fix token actor marking

---

src/templates/actor/tabs/SkillsTab.hbs

Fixes #1542 without resorting to the suggested hack. Just replicated the behaviour by readding the class from #1473 .

fix: #1473 again class got lost. Fixes #1542.

---

src/module/actor/SR5Actor.ts
src/module/actor/sheets/SR5MatrixActorSheet.ts
src/module/flows/MatrixTargetingFlow.ts
src/module/handlebars/ItemLineHelpers.ts
src/module/tests/flows/MatrixTestDataFlow.ts

Fixes #1552
Previously all wireless devices were collected for targeting. 
The icon targeting approach is still very prototypi'. While adding an additional `isRunningSilent` check will remove those icons from targeting, the additional `runningSilent` property is likely unused for now.
It was originally part of a genereric approach of collecting marked documents, which is reused here for targeted documents (which might also be marked). This causes duplicate data to be present.
I've added a task to the Matrix 2.0 board to clean this up.
An additional requirement for matrix targets will be a GM and player flow that allows players to hack non-wireless targets using a direct connection. Added another task to the Matrix 2.0 board.

[BUG] Silent Matrix icons are still visible through target list

---

src/module/template.ts

Fixes #1590
The reported issue was related to Foundry Template DataModel reporting it doesn't want an empty string even though we gave it a Color object RGBA string represation. Giving the Color instance directly restored previous behavior.
Other issues were events getting default PointerEvents intsead of PiXi InteractionEvents, due to the usage of the HTMLCanvasElement as event source instead of the TemplateLayer given by Foundry into activateListeners.

[BUG] Place Template Failing Validation

---

src/module/item/flows/MatrixNetworkFlow.ts
src/module/types/template/Matrix.ts
src/module/types/template/MatrixNetwork.ts

Fixes #1591
Issue is related to network connections being stored in `DataStorage` instead of on document. We've had the same issue with PAN / WAN devices and their shown connected icons not updating across user sessions.
I've used the same solution here - updating a dummy system field -, though this will not update unrelated sheets any user could have open for any actor which might be in any way showing the updated actors network state. For those, we'd have to use another approch, which I added my first thought to here: https://github.com/users/SR5-FoundryVTT/projects/3/views/5?sliceBy%5Bvalue%5D=To+do&pane=issue&itemId=130977972
Until then, the "Refresh"-button must be used for all other actors to update their icons list.

[BUG] Player Grid Hopping Doesnt Update On GM Side

---

src/module/actor/sheets/SR5BaseActorSheet.ts

Fixes #1607
hot_sim property didn't get hard set when moving into meatspace mode.

[BUG] Switching initiative back from hot SIM to meat doesn't remove hot sim modifier

---

src/module/actor/SR5Actor.ts

Fixes #1597
This keeps previous functionality of only allowing a single equipped device, while also allowing to unequipp it.

[BUG] Devices Can't Be Deactivated From Gear Tab

---

src/module/tests/SuccessTest.ts

Fixes #1604
@BM123499 Do you remember the reasoning for chaning the `SuccessTest.extendedHits` getter to a method?
The issue here is caused by handlebar using it as a property as it can't directly call methods outside of helpers, far as I know.

[BUG] Extended tests doesn't show extended hits anymore on chat message
